# Variables and Distributions

Time to play in data land! We began our journey with a promise to help you understand and quantify your uncertainty. Now, we shift to the heart and soul of data - the distribution. Every variable has a distribution, and understanding that distribution is key to understanding the data. We will explore the most common distributions and how to use them to make sense of your data. Let's get started, shall we?

## Learning Objectives

1.  Understand the concept of a variable and how they may be represented in data.
2.  Learn about the most common distributions and how to use them.
3.  Understand the concept of a probability density function and how to use it.
4.  Learn how to use distributions to make predictions and quantify uncertainty.

## Variables

Everything we wish to understand about people or things comes in the form of a variable. If I want to know why people like chocolate ice cream, I must assign some form of numerical value to "like" such that I can learn from my observations. Why?  Learning via these methods require data.  Each variable is a set of observations. We assign numbers to observations and these observations serve as our data. Each variable is unique. Some variables contain data that represent a singular characteristic of a person or thing; other variables contain data that represent multiple characteristics. These characteristics we often call constructs in psychological science. From this point forward, we shall refer to the underlying characteristic that we measure as the construct.

Let's examine this a bit more closely. Consider two variables height and weight. Height is a variable that contains data representing a singular characteristic of a person - the length of the person's body when standing. Changes in height measures a singular characteristic of a person that can be altered only by skeletal growth/decay. Weight, on the other hand, contains data representing a single characteristic (mass) but determined by many contributing factors (e.g., water, fat, muscle, bone, etc.). Combined, height and weight make a composite variable called Body Mass Index (BMI) - [an often used but derided](https://www.health.harvard.edu/blog/how-useful-is-the-body-mass-index-bmi-201603309339) predictor of health and well-being.


|                    | Singular Construct | Multiple Constructs |
|--------------------|--------------------|---------------------|
| **Singular Cause** | IDEAL (Height)     | Less IDEAL (Weight) |
| **Multiple Cause** | Most Common (g)    | REALLY BAD (BMI)    |

In the table above, we see that the ideal variable is one that contains data representing a singular characteristic of a person and is determined by a singular cause. Similarly, we see BMI labeled as "REALLY BAD."  These are abstractions right now but they become important as we delve into psychological science and the uncertainty around our constructs.  

### Types of Variables

We have many types of variables to choose from when we begin our journey into data land. Each type of variable has its own unique characteristics and uses. Let's explore the most common types of variables. Decades ago, psychological scientists were hamstrung by W.W. Stevens levels of measurement. Stevens argued that there were four levels of measurement: nominal, ordinal, interval, and ratio. These levels of measurement were used to determine the permissible analyses based solely on the logic of arithmetic. Times have changed but arithmetic remains the same. The argument, however, that the level of measurement dictates the analysis is simply untrue. We may do whatever analysis we choose. Which ones make sense depends upon a whole host of factors that we address in this book. So, keep reading. Below is a much easier taxonomy for understanding variables.

#### Continuous Variables

Continuous variables are those that can take on any value within a range. These variables are often measured and can be divided into smaller and smaller units. Examples of continuous variables include height, weight, and temperature. We care not only about the integer values (e.g., 5 feet) but also the decimal values as well (e.g., 5.5 feet). Continuous variables are the most commonly assumed type of variable in psychological science. We emphasize assumed here because we see many instances where continuity - that is, the continuous nature of a variable - makes no sense and yet, in those instances, are treated as such. EGAD! What are we to do? Well, we must learn. So, a continuous variable is a variable containing any value between a range of possible values including negative and positive infinity.

#### Categorical Variables

Categorical variables are those that contain any value within a set.  Consider `pet` as a variable that may contain any number of possible pets that people keep (e.g., dog, cat, mouse, fish, etc.). Categorical variables have some special properties in that they are non-numeric.  How do we compute statistics on non-numeric data?  Well, we shall discuss the point later but know that categorical variables at some point must be converted into numbers so that they may be analyzed using statistics.  We shall discuss this point later.  For now, understand that categorical variables are those that contain any value within a set of possible values and those values are often alphanumeric (i.e., dog, cat, mouse, fish) but need not be so (i.e., dog1, cat42, m0use, f1sh, etc.).

#### Discrete Variables

Some variables can take only certain values.  Take, for example, a Likert scale.  A scale that ranges from 0 to 5 usually offers the respondent only integer values (i.e., 0, 1, 2, 3, 4, or 5). Technically, a Likert scale is a discrete variable that we treat as a continuous variable.  We shall return to this point later.  For now, understand the discrete variables are variables that may take only specific values.  Often, these variables are either dichotomous (e.g., 0 or 1) or ordinal (e.g., 1, 2, 3, 4, 5).




#### Ordinal Variables

### Representing Variables Numerically

### Plotting Variables

#### Histograms

## Shapes

## Distributions

### Names for Shapes

### Probability Density Functions
