project:
  type: book
  output-dir: _book

book:
  title: "Graduate Statistics in Plain Ol' English"
  author: "Patrick E. McKnight and Simone C. McKnight"
  date: last-modified
  date-format: long
  chapters:
    - index.qmd
    - preface.qmd
    - author.qmd
    - intro.qmd
    - references.qmd
  cover-image: img/MRES2wbg.png
  repo-url: https://github.com/pem725/GradStats-Book
  repo-branch: main
      
bibliography: [statbook.bib, packages.bib]
biblio-style: apalike

output:
  html:
    theme: darkly
    highlight: pygments
    
link-citations: true
github-repo: pem725/GradStats-Book
description: "A comprehensive graduate statistics book suitable for social and behavioral sciences. Our approach is to provide interested students a gentle guide to the rudiments of statistical estimation and inference."
twitter-handle: pem725
cover-image: img/MRES2wbg.png
colorlinks: true
graphics: true