project:
  type: book
  output-dir: _book

book:
  title: "Statistics by Us for You"
  author: "Patrick E. McKnight and Simone C. McKnight"
  date: last-modified
  date-format: long
  chapters:
    - index.qmd
    - preface.qmd
    - author.qmd
    - intro.qmd
    - part: "The Basics"
      chapters:
        - 02-distributions.qmd
        - 03-CTmeasures.qmd
        - 04-Dmeasures.qmd
        - 05-datacleaning.qmd
    - part: "Making Inferences with Data"
      chapters:
        - 06-zdistribution.qmd
        - 07-covariance.qmd
        - 08-hypothesistesting.qmd
        - 09-statisticalpower.qmd
    - part: "Checking Our Data"
      chapters:
        - 10-reliability.qmd
        - 11-validity.qmd
    - part: "Using Models"
      chapters:
        - 12-GLMcovariance.qmd
        - 13-pointbiserialcorrelation.qmd
        - 14-bivariateregression.qmd
        - 15-MRC.qmd
        - 16-ANOVAandGLM.qmd
        - 17-basicANOVA.qmd
    - references.qmd
  cover-image: img/MRES2wbg.png
  repo-url: https://github.com/pem725/GradStats-Book
  repo-branch: main
      
bibliography: [statbook.bib, packages.bib]
biblio-style: apalike

output:
  html:
    theme: darkly
    highlight: pygments
    
link-citations: true
github-repo: pem725/GradStats-Book
description: "A comprehensive graduate statistics book suitable for social and behavioral sciences. Our approach is to provide interested students a gentle guide to the rudiments of statistical estimation and inference."
twitter-handle: pem725
cover-image: img/MRES2wbg.png
colorlinks: true
graphics: true