---
title: "Module 1: Getting Started"
---

# Setup the environment


```{r setup}
#| echo: true
#| messages: false
#| warning: false
#| error: false
library(psych)
library(tidyverse)
library(kableExtra)
library(plotly)
library(GGally)


```

# Some data

```{r}
#| messages: false
#| echo: true
#| warning: false
#| error: false

# load the mtcars data
data(mtcars)
describe(mtcars)

```

# Some plots

```{r}
#| messages: false
#| echo: true
#| warning: false
#| error: false

# create a histogram of mpg
hist(mtcars$mpg)

# create a histogram of hp
hist(mtcars$hp)

```

# Data transformation

```{r}
#| messages: false
#| echo: true
#| warning: false
#| error: false

# standardize the mpg variable
mpg.z <- scale(mtcars$mpg)


# create a histogram of the standardized mpg variable
hist(mpg.z)

hist(mtcars$mpg)

# create a histogram and density plot of mpg using ggplot
library(ggplot2)
ggplot(mtcars, aes(x=mpg)) + geom_histogram(binwidth=5, fill="blue", color="black") + geom_density(alpha=.2, fill="red")

# please overlay a density plot on the histogram
ggplot(mtcars, aes(x=mpg)) + geom_histogram(binwidth=5, fill="blue", color="black") + geom_density(alpha=.2, fill="red")

# fix the axes so that the density and histogram agree on the y axis
ggplot(mtcars, aes(x=mpg)) + geom_histogram(binwidth=5, fill="blue", color="black", aes(y=..density..)) + geom_density(alpha=.2, fill="red")



```

```{r}
#| messages: false
#| echo: true
#| warning: false
#| error: false

# create a scatterplot of mpg vs. hp
ggplot(mtcars, aes(x=hp, y=mpg)) + geom_point()

# create a scatterplot of mpg vs. hp with a regression line
ggplot(mtcars, aes(x=hp, y=mpg)) + geom_point() + geom_smooth(method="lm")

# create a scatterplot of mpg vs. hp with a regression line and a loess line
ggplot(mtcars, aes(x=hp, y=mpg)) + geom_point() + geom_smooth(method="lm") + geom_smooth(method="loess")

```

```{r}
#| messages: false
#| echo: true
#| warning: false
#| error: false

# read a google sheet into R
library(googlesheets4)

# read the data from the google sheet
dat1 <- read_sheet('https://docs.google.com/spreadsheets/d/1bWP0sNJnXOhquYA52CVDQOYVDtNrkaGYIped2ALuYk4/edit?gid=19106208#gid=19106208')

# print the data
kable(head(dat1))

describe(dat1)

```

# Describe the Data

```{r}
#| messages: false
#| echo: true
#| warning: false
#| error: false



p <- dat1[,c(1:3,11:12)] %>%
  ggpairs(aes(colour=sex))

ggplotly(p)

```

# What to make of data

```{r}
#| echo: true
#| messages: false
#| warning: false
#| error: false

data(mtcars)

plot(mtcars$mpg)

mtcars$mpg2 <- mtcars$mpg
mtcars$mpg2[5] <- 300

mtcars$mpg2[30] <- .0000001
plot(mtcars$mpg2)

plot(mtcars$mpg2[-c(5,30)])

hist(mtcars$mpg)
hist(mtcars$mpg2)

mtcars$mpg.z <- scale(mtcars$mpg)
mtcars$mpg.log <- log(mtcars$mpg)
mtcars$mpg.sqrt <- sqrt(mtcars$mpg)

plot(mtcars$mpg.z)
plot(mtcars$mpg.log)
plot(mtcars$mpg.sqrt)

# ggplot for mpg
ggplot(mtcars, aes(x=mpg)) + geom_histogram(binwidth=5, fill="blue", color="black") + geom_density(alpha=.2, fill="red")

# annotate the ggplot with a normal curve and put them both on a density y axis
ggplot(mtcars, aes(x=mpg)) + geom_histogram(binwidth=5, fill="blue", color="black", aes(y=..density..)) + geom_density(alpha=.2, fill="red") + stat_function(fun=dnorm, args=list(mean=mean(mtcars$mpg), sd=sd(mtcars$mpg)), color="blue")





```


