* Loads appendix-items.csv. Generated by setup/make_data.R - do not hand-edit.
GET DATA /TYPE=TXT /FILE='data/sim/appendix-items.csv'
  /DELIMITERS=',' /QUALIFIER='"' /FIRSTCASE=2
  /VARIABLES=item1 F16.6 item2 F16.6 item3 F16.6 item4 F16.6.
