* Loads ch01-shapes.csv. Generated by setup/make_data.R - do not hand-edit.
GET DATA /TYPE=TXT /FILE='data/sim/ch01-shapes.csv'
  /DELIMITERS=',' /QUALIFIER='"' /FIRSTCASE=2
  /VARIABLES=Normal F16.6 Uniform F16.6 Binomial F16.6 Poisson F16.6.
