* Loads ch03-spread.csv. Generated by setup/make_data.R - do not hand-edit.
GET DATA /TYPE=TXT /FILE='data/sim/ch03-spread.csv'
  /DELIMITERS=',' /QUALIFIER='"' /FIRSTCASE=2
  /VARIABLES=group A24 value F16.6.
