* Loads ch09-attenuation.csv. Generated by setup/make_data.R - do not hand-edit.
GET DATA /TYPE=TXT /FILE='data/sim/ch09-attenuation.csv'
  /DELIMITERS=',' /QUALIFIER='"' /FIRSTCASE=2
  /VARIABLES=Tx F16.6 Ty F16.6 Ox F16.6 Oy F16.6.
