* Loads ch10-validity.csv. Generated by setup/make_data.R - do not hand-edit.
GET DATA /TYPE=TXT /FILE='data/sim/ch10-validity.csv'
  /DELIMITERS=',' /QUALIFIER='"' /FIRSTCASE=2
  /VARIABLES=anxiety_true F16.6 new_scale F16.6 old_scale F16.6 verbal F16.6.
