* Loads ch16-pets.csv. Generated by setup/make_data.R - do not hand-edit.
GET DATA /TYPE=TXT /FILE='data/sim/ch16-pets.csv'
  /DELIMITERS=',' /QUALIFIER='"' /FIRSTCASE=2
  /VARIABLES=x F16.6 happy F16.6 pet A24 mess A24 sad F16.6 passed F16.6.
