* Loads ch19-items.csv. Generated by setup/make_data.R - do not hand-edit.
GET DATA /TYPE=TXT /FILE='data/sim/ch19-items.csv'
  /DELIMITERS=',' /QUALIFIER='"' /FIRSTCASE=2
  /VARIABLES=x1 F16.6 x2 F16.6 x3 F16.6 x4 F16.6 x5 F16.6 x6 F16.6.
