* Loads ch20-cfa.csv. Generated by setup/make_data.R - do not hand-edit.
GET DATA /TYPE=TXT /FILE='data/sim/ch20-cfa.csv'
  /DELIMITERS=',' /QUALIFIER='"' /FIRSTCASE=2
  /VARIABLES=a1 F16.6 a2 F16.6 a3 F16.6 a4 F16.6 b1 F16.6 b2 F16.6 b3 F16.6 b4 F16.6.
