* Loads ch21-invariance.csv. Generated by setup/make_data.R - do not hand-edit.
GET DATA /TYPE=TXT /FILE='data/sim/ch21-invariance.csv'
  /DELIMITERS=',' /QUALIFIER='"' /FIRSTCASE=2
  /VARIABLES=grp A24 trait F16.6 bias F16.6 composite F16.6.
