* Loads ch24-fork.csv. Generated by setup/make_data.R - do not hand-edit.
GET DATA /TYPE=TXT /FILE='data/sim/ch24-fork.csv'
  /DELIMITERS=',' /QUALIFIER='"' /FIRSTCASE=2
  /VARIABLES=Z F16.6 X F16.6 Y F16.6.
