* Loads ch24-collider.csv. Generated by setup/make_data.R - do not hand-edit.
GET DATA /TYPE=TXT /FILE='data/sim/ch24-collider.csv'
  /DELIMITERS=',' /QUALIFIER='"' /FIRSTCASE=2
  /VARIABLES=X F16.6 Y F16.6 Z F16.6.
