* Loads ch27-bdi.csv. Generated by setup/make_data.R - do not hand-edit.
GET DATA /TYPE=TXT /FILE='data/sim/ch27-bdi.csv'
  /DELIMITERS=',' /QUALIFIER='"' /FIRSTCASE=2
  /VARIABLES=sadness F16.6 pessimism F16.6 past_failure F16.6 loss_pleasure F16.6 guilt F16.6 punishment F16.6 self_dislike F16.6 self_critical F16.6 suicidal F16.6 crying F16.6 agitation F16.6 loss_interest F16.6 indecision F16.6 worthlessness F16.6 loss_energy F16.6 sleep F16.6 irritability F16.6 appetite F16.6 concentration F16.6 tiredness F16.6 loss_sex_interest F16.6.
