* Loads ch28-curiosity.csv. Generated by setup/make_data.R - do not hand-edit.
GET DATA /TYPE=TXT /FILE='data/sim/ch28-curiosity.csv'
  /DELIMITERS=',' /QUALIFIER='"' /FIRSTCASE=2
  /VARIABLES=item1 F16.6 item2 F16.6 item3 F16.6 item4 F16.6 item5 F16.6 item6 F16.6 item7 F16.6 item8 F16.6 item9 F16.6 item10 F16.6 item11 F16.6 item12 F16.6.
