* Loads ch29-missing.csv. Generated by setup/make_data.R - do not hand-edit.
GET DATA /TYPE=TXT /FILE='data/sim/ch29-missing.csv'
  /DELIMITERS=',' /QUALIFIER='"' /FIRSTCASE=2
  /VARIABLES=z F16.6 y F16.6 p_miss F16.6 y_obs F16.6.
