* Loads ch34-wellbeing.csv. Generated by setup/make_data.R - do not hand-edit.
GET DATA /TYPE=TXT /FILE='data/sim/ch34-wellbeing.csv'
  /DELIMITERS=',' /QUALIFIER='"' /FIRSTCASE=2
  /VARIABLES=group A24 weeks F16.6 wellbeing F16.6.
